
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.NETResources
{
	public partial class ResXEditorWidget
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action StringResourcesAction;
		private global::Gtk.Action OtherAction;
		private global::Gtk.RadioAction StringsAction;
		private global::Gtk.RadioAction ImagesAction;
		private global::Gtk.RadioAction IconsAction;
		private global::Gtk.RadioAction AudioAction;
		private global::Gtk.RadioAction OtherFilesAction;
		private global::Gtk.RadioAction OtherEmbeddedAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Button AddBtn;
		private global::Gtk.Button DeleteBtn;
		private global::Gtk.Label AccessorLabel;
		private global::Gtk.ComboBox CodeGenCombo;
		private global::Gtk.Notebook pagesNotebook;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label FilterLabel;
		private global::MonoDevelop.Components.SearchEntry filterSearchEntry;
		private global::Gtk.ScrolledWindow entriesScrolledWindow;
		private global::Gtk.TreeView entriesTV;
		private global::MonoDevelop.NETResources.ResXObjectIconWidget objectIconWidget;
		private global::Gtk.Label label4;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Toolbar selectorTB;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.NETResources.ResXEditorWidget
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.StringResourcesAction = new global::Gtk.Action ("StringResourcesAction", global::Mono.Unix.Catalog.GetString ("String Resources"), null, null);
			this.StringResourcesAction.HideIfEmpty = false;
			this.StringResourcesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("String Resources");
			w2.Add (this.StringResourcesAction, null);
			this.OtherAction = new global::Gtk.Action ("OtherAction", global::Mono.Unix.Catalog.GetString ("Other Resources"), null, null);
			this.OtherAction.HideIfEmpty = false;
			this.OtherAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Other Resources");
			w2.Add (this.OtherAction, null);
			this.StringsAction = new global::Gtk.RadioAction ("StringsAction", global::Mono.Unix.Catalog.GetString ("Strings"), null, null, 0);
			this.StringsAction.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.StringsAction.HideIfEmpty = false;
			this.StringsAction.IsImportant = true;
			this.StringsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Strings");
			w2.Add (this.StringsAction, null);
			this.ImagesAction = new global::Gtk.RadioAction ("ImagesAction", global::Mono.Unix.Catalog.GetString ("Images"), null, null, 0);
			this.ImagesAction.Group = this.StringsAction.Group;
			this.ImagesAction.HideIfEmpty = false;
			this.ImagesAction.IsImportant = true;
			this.ImagesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Images");
			w2.Add (this.ImagesAction, null);
			this.IconsAction = new global::Gtk.RadioAction ("IconsAction", global::Mono.Unix.Catalog.GetString ("Icons"), null, null, 0);
			this.IconsAction.Group = this.StringsAction.Group;
			this.IconsAction.HideIfEmpty = false;
			this.IconsAction.IsImportant = true;
			this.IconsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Icons");
			w2.Add (this.IconsAction, null);
			this.AudioAction = new global::Gtk.RadioAction ("AudioAction", global::Mono.Unix.Catalog.GetString ("Audio"), null, null, 0);
			this.AudioAction.Group = this.StringsAction.Group;
			this.AudioAction.HideIfEmpty = false;
			this.AudioAction.IsImportant = true;
			this.AudioAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Audio");
			w2.Add (this.AudioAction, null);
			this.OtherFilesAction = new global::Gtk.RadioAction ("OtherFilesAction", global::Mono.Unix.Catalog.GetString ("Other Files"), null, null, 0);
			this.OtherFilesAction.Group = this.AudioAction.Group;
			this.OtherFilesAction.HideIfEmpty = false;
			this.OtherFilesAction.IsImportant = true;
			this.OtherFilesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Other Files");
			w2.Add (this.OtherFilesAction, null);
			this.OtherEmbeddedAction = new global::Gtk.RadioAction ("OtherEmbeddedAction", global::Mono.Unix.Catalog.GetString ("Other Embedded"), null, null, 0);
			this.OtherEmbeddedAction.Group = this.AudioAction.Group;
			this.OtherEmbeddedAction.HideIfEmpty = false;
			this.OtherEmbeddedAction.IsImportant = true;
			this.OtherEmbeddedAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Other Embedded");
			w2.Add (this.OtherEmbeddedAction, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "MonoDevelop.NETResources.ResXEditorWidget";
			// Container child MonoDevelop.NETResources.ResXEditorWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.AddBtn = new global::Gtk.Button ();
			this.AddBtn.CanFocus = true;
			this.AddBtn.Name = "AddBtn";
			this.AddBtn.UseUnderline = true;
			// Container child AddBtn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.LabelProp = global::Mono.Unix.Catalog.GetString ("_Add Resource");
			w7.UseUnderline = true;
			w4.Add (w7);
			w3.Add (w4);
			this.AddBtn.Add (w3);
			this.hbox4.Add (this.AddBtn);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.AddBtn]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.DeleteBtn = new global::Gtk.Button ();
			this.DeleteBtn.CanFocus = true;
			this.DeleteBtn.Name = "DeleteBtn";
			this.DeleteBtn.UseUnderline = true;
			// Container child DeleteBtn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w13 = new global::Gtk.HBox ();
			w13.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w13.Add (w14);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w16 = new global::Gtk.Label ();
			w16.LabelProp = global::Mono.Unix.Catalog.GetString ("_Delete Resource");
			w16.UseUnderline = true;
			w13.Add (w16);
			w12.Add (w13);
			this.DeleteBtn.Add (w12);
			this.hbox4.Add (this.DeleteBtn);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.DeleteBtn]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.AccessorLabel = new global::Gtk.Label ();
			this.AccessorLabel.Name = "AccessorLabel";
			this.AccessorLabel.Xalign = 1F;
			this.AccessorLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Code Generation");
			this.hbox4.Add (this.AccessorLabel);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.AccessorLabel]));
			w21.Position = 2;
			// Container child hbox4.Gtk.Box+BoxChild
			this.CodeGenCombo = global::Gtk.ComboBox.NewText ();
			this.CodeGenCombo.AppendText (global::Mono.Unix.Catalog.GetString ("No Generation"));
			this.CodeGenCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Internal Class"));
			this.CodeGenCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Public Class"));
			this.CodeGenCombo.Name = "CodeGenCombo";
			this.CodeGenCombo.Active = 0;
			this.hbox4.Add (this.CodeGenCombo);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.CodeGenCombo]));
			w22.Position = 3;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.pagesNotebook = new global::Gtk.Notebook ();
			this.pagesNotebook.CanFocus = true;
			this.pagesNotebook.Name = "pagesNotebook";
			this.pagesNotebook.CurrentPage = 1;
			this.pagesNotebook.ShowBorder = false;
			this.pagesNotebook.ShowTabs = false;
			// Container child pagesNotebook.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.FilterLabel = new global::Gtk.Label ();
			this.FilterLabel.Name = "FilterLabel";
			this.FilterLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Filter:");
			this.hbox1.Add (this.FilterLabel);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.FilterLabel]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.filterSearchEntry = new global::MonoDevelop.Components.SearchEntry ();
			this.filterSearchEntry.Name = "filterSearchEntry";
			this.filterSearchEntry.ForceFilterButtonVisible = false;
			this.filterSearchEntry.IsCheckMenu = false;
			this.filterSearchEntry.ActiveFilterID = 0;
			this.filterSearchEntry.Ready = false;
			this.filterSearchEntry.HasFocus = false;
			this.hbox1.Add (this.filterSearchEntry);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.filterSearchEntry]));
			w25.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.entriesScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.entriesScrolledWindow.CanFocus = true;
			this.entriesScrolledWindow.Name = "entriesScrolledWindow";
			this.entriesScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child entriesScrolledWindow.Gtk.Container+ContainerChild
			this.entriesTV = new global::Gtk.TreeView ();
			this.entriesTV.CanFocus = true;
			this.entriesTV.Name = "entriesTV";
			this.entriesScrolledWindow.Add (this.entriesTV);
			this.vbox2.Add (this.entriesScrolledWindow);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.entriesScrolledWindow]));
			w28.Position = 1;
			this.pagesNotebook.Add (this.vbox2);
			// Container child pagesNotebook.Gtk.Notebook+NotebookChild
			this.objectIconWidget = new global::MonoDevelop.NETResources.ResXObjectIconWidget ();
			this.objectIconWidget.Events = ((global::Gdk.EventMask)(256));
			this.objectIconWidget.Name = "objectIconWidget";
			this.pagesNotebook.Add (this.objectIconWidget);
			global::Gtk.Notebook.NotebookChild w30 = ((global::Gtk.Notebook.NotebookChild)(this.pagesNotebook [this.objectIconWidget]));
			w30.Position = 1;
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("page3");
			this.pagesNotebook.SetTabLabel (this.objectIconWidget, this.label4);
			this.label4.ShowAll ();
			this.vbox1.Add (this.pagesNotebook);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.pagesNotebook]));
			w31.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='selectorTB'><toolitem name='StringsAction' action='StringsAction'/><toolitem name='ImagesAction' action='ImagesAction'/><toolitem name='IconsAction' action='IconsAction'/><toolitem name='AudioAction' action='AudioAction'/><toolitem name='OtherFilesAction' action='OtherFilesAction'/><toolitem name='OtherEmbeddedAction' action='OtherEmbeddedAction'/></toolbar></ui>");
			this.selectorTB = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/selectorTB")));
			this.selectorTB.Name = "selectorTB";
			this.selectorTB.ShowArrow = false;
			this.hbox3.Add (this.selectorTB);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.selectorTB]));
			w32.Position = 0;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Show ();
			this.StringsAction.Activated += new global::System.EventHandler (this.OnSelectorTBActionActivated);
			this.ImagesAction.Activated += new global::System.EventHandler (this.OnSelectorTBActionActivated);
			this.IconsAction.Activated += new global::System.EventHandler (this.OnSelectorTBActionActivated);
			this.AudioAction.Activated += new global::System.EventHandler (this.OnSelectorTBActionActivated);
			this.OtherFilesAction.Activated += new global::System.EventHandler (this.OnSelectorTBActionActivated);
			this.OtherEmbeddedAction.Activated += new global::System.EventHandler (this.OnSelectorTBActionActivated);
			this.AddBtn.Clicked += new global::System.EventHandler (this.OnAddBtnClick);
			this.DeleteBtn.Clicked += new global::System.EventHandler (this.OnDeleteBtnClick);
			this.CodeGenCombo.Changed += new global::System.EventHandler (this.OnCodeGenComboChanged);
		}
	}
}
