
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.NETResources
{
	public partial class ResXObjectIconWidget
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action efwdsfasdfAction;
		private global::Gtk.Action AddResourceAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.IconView entriesIV;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.NETResources.ResXObjectIconWidget
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.efwdsfasdfAction = new global::Gtk.Action ("efwdsfasdfAction", global::Mono.Unix.Catalog.GetString ("efwdsfasdf"), null, null);
			this.efwdsfasdfAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("efwdsfasdf");
			w2.Add (this.efwdsfasdfAction, null);
			this.AddResourceAction = new global::Gtk.Action ("AddResourceAction", global::Mono.Unix.Catalog.GetString ("Add Resource..."), null, null);
			this.AddResourceAction.IsImportant = true;
			this.AddResourceAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Resource...");
			w2.Add (this.AddResourceAction, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "MonoDevelop.NETResources.ResXObjectIconWidget";
			// Container child MonoDevelop.NETResources.ResXObjectIconWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.entriesIV = new global::Gtk.IconView ();
			this.entriesIV.CanFocus = true;
			this.entriesIV.Name = "entriesIV";
			this.entriesIV.ItemWidth = 100;
			this.vbox1.Add (this.entriesIV);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.entriesIV]));
			w3.Position = 0;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
		}
	}
}
