
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.NETResources
{
	public partial class ResXEditorWidget
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action StringResourcesAction;
		private global::Gtk.Action OtherAction;
		private global::Gtk.ToggleAction StringResourcesAction1;
		private global::Gtk.ToggleAction OtherResourcesAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.Notebook notebook1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label FilterLabel;
		private global::MonoDevelop.Components.SearchEntry filterSearchEntry;
		private global::Gtk.Label AccessorLabel;
		private global::Gtk.ComboBox AccessorCombo;
		private global::Gtk.ScrolledWindow entriesScrolledWindow;
		private global::Gtk.TreeView entriesTreeView;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Toolbar pagesToolBar;
		private global::Gtk.ProgressBar translationProgressBar;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.NETResources.ResXEditorWidget
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.StringResourcesAction = new global::Gtk.Action ("StringResourcesAction", global::Mono.Unix.Catalog.GetString ("String Resources"), null, null);
			this.StringResourcesAction.HideIfEmpty = false;
			this.StringResourcesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("String Resources");
			w2.Add (this.StringResourcesAction, null);
			this.OtherAction = new global::Gtk.Action ("OtherAction", global::Mono.Unix.Catalog.GetString ("Other Resources"), null, null);
			this.OtherAction.HideIfEmpty = false;
			this.OtherAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Other Resources");
			w2.Add (this.OtherAction, null);
			this.StringResourcesAction1 = new global::Gtk.ToggleAction ("StringResourcesAction1", global::Mono.Unix.Catalog.GetString ("String Resources"), null, null);
			this.StringResourcesAction1.HideIfEmpty = false;
			this.StringResourcesAction1.IsImportant = true;
			this.StringResourcesAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("String Resources");
			w2.Add (this.StringResourcesAction1, null);
			this.OtherResourcesAction = new global::Gtk.ToggleAction ("OtherResourcesAction", global::Mono.Unix.Catalog.GetString ("Other Resources"), null, null);
			this.OtherResourcesAction.HideIfEmpty = false;
			this.OtherResourcesAction.IsImportant = true;
			this.OtherResourcesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Other Resources");
			w2.Add (this.OtherResourcesAction, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "MonoDevelop.NETResources.ResXEditorWidget";
			// Container child MonoDevelop.NETResources.ResXEditorWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			this.notebook1.ShowBorder = false;
			this.notebook1.ShowTabs = false;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.FilterLabel = new global::Gtk.Label ();
			this.FilterLabel.Name = "FilterLabel";
			this.FilterLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Filter:");
			this.hbox1.Add (this.FilterLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.FilterLabel]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.filterSearchEntry = new global::MonoDevelop.Components.SearchEntry ();
			this.filterSearchEntry.Name = "filterSearchEntry";
			this.filterSearchEntry.ForceFilterButtonVisible = false;
			this.filterSearchEntry.IsCheckMenu = false;
			this.filterSearchEntry.ActiveFilterID = 0;
			this.filterSearchEntry.Ready = false;
			this.filterSearchEntry.HasFocus = false;
			this.hbox1.Add (this.filterSearchEntry);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.filterSearchEntry]));
			w4.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.AccessorLabel = new global::Gtk.Label ();
			this.AccessorLabel.Name = "AccessorLabel";
			this.AccessorLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Accessor");
			this.hbox1.Add (this.AccessorLabel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.AccessorLabel]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.AccessorCombo = global::Gtk.ComboBox.NewText ();
			this.AccessorCombo.AppendText (global::Mono.Unix.Catalog.GetString ("No Generation"));
			this.AccessorCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Internal"));
			this.AccessorCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Public"));
			this.AccessorCombo.Name = "AccessorCombo";
			this.hbox1.Add (this.AccessorCombo);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.AccessorCombo]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.entriesScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.entriesScrolledWindow.CanFocus = true;
			this.entriesScrolledWindow.Name = "entriesScrolledWindow";
			this.entriesScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child entriesScrolledWindow.Gtk.Container+ContainerChild
			this.entriesTreeView = new global::Gtk.TreeView ();
			this.entriesTreeView.CanFocus = true;
			this.entriesTreeView.Name = "entriesTreeView";
			this.entriesScrolledWindow.Add (this.entriesTreeView);
			this.vbox2.Add (this.entriesScrolledWindow);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.entriesScrolledWindow]));
			w9.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='pagesToolBar'><toolitem name='StringResourcesAction1' action='StringResourcesAction1'/><toolitem name='OtherResourcesAction' action='OtherResourcesAction'/></toolbar></ui>");
			this.pagesToolBar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/pagesToolBar")));
			this.pagesToolBar.Name = "pagesToolBar";
			this.pagesToolBar.ShowArrow = false;
			this.hbox2.Add (this.pagesToolBar);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.pagesToolBar]));
			w10.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.translationProgressBar = new global::Gtk.ProgressBar ();
			this.translationProgressBar.Name = "translationProgressBar";
			this.hbox2.Add (this.translationProgressBar);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.translationProgressBar]));
			w11.Position = 1;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.notebook1.Add (this.vbox2);
			this.vbox1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
			w14.Position = 0;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Show ();
		}
	}
}
