
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.NETResources
{
	public partial class ResXObjectWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.NETResources.ResXObjectWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.NETResources.ResXObjectWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
