
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.NETResources
{
	public partial class ResXObjectIconWidget
	{
		private global::Gtk.IconView entriesIV;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.NETResources.ResXObjectIconWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.NETResources.ResXObjectIconWidget";
			// Container child MonoDevelop.NETResources.ResXObjectIconWidget.Gtk.Container+ContainerChild
			this.entriesIV = new global::Gtk.IconView ();
			this.entriesIV.CanFocus = true;
			this.entriesIV.Name = "entriesIV";
			this.entriesIV.ItemWidth = 150;
			this.Add (this.entriesIV);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
