
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.NETResources
{
	public partial class ResXObjectIconWidget
	{
		private global::Gtk.IconView iconview2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.NETResources.ResXObjectIconWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.NETResources.ResXObjectIconWidget";
			// Container child MonoDevelop.NETResources.ResXObjectIconWidget.Gtk.Container+ContainerChild
			this.iconview2 = new global::Gtk.IconView ();
			this.iconview2.CanFocus = true;
			this.iconview2.Name = "iconview2";
			this.iconview2.ItemWidth = 150;
			this.Add (this.iconview2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
